# Generated by Django 4.1.3 on 2022-11-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=25)),
                ('co', models.FloatField()),
                ('no', models.FloatField()),
                ('no2', models.FloatField()),
                ('o3', models.FloatField()),
                ('so2', models.FloatField()),
                ('pm2_5', models.FloatField()),
                ('pm10', models.FloatField()),
                ('nh3', models.FloatField()),
            ],
        ),
    ]
