# Generated by Django 4.1.3 on 2022-11-18 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComponentsData',
        ),
    ]
